/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package lab;
/** 
 * Класс приложения выводящий сообщение.
 * @author Nikita Matsnev
 * @version 1.0.1
*/
public class App {
    public static void main(String[] args){
        // Task 1
        System.out.println("Starting project");
        // Task 2
        byte v_byte = 120;
        short v_short = 129;
        char v_char = 'a'; // add ''
        int v_int = 65999;
        long v_long = Long.parseUnsignedLong("4294967296"); // var is overflow
        float v_float = 0.33333334f; // add f 
        double v_double = 0.33333333333;
        boolean v_boolean = true; // change var name

        System.out.println("v_byte: " + v_byte);
        System.out.println("v_short: " + v_short);
        System.out.println("v_char: " + v_char);
        System.out.println("v_int: " + v_int);
        System.out.println("v_long: " + v_long);
        System.out.println("v_float: " + v_float);
        System.out.println("v_double: " + v_double);
        System.out.println("v_boolean: " + v_boolean);
    }
}
