/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package lab;
/** 
 * Класс приложения выводящий сообщение.
 * @author Nikita Matsnev
 * @version 1.0.1
*/
public class App {
    public static void main(String[] args){
        System.out.println("Starting project");
    }
}
