/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package lab;
/** 
 * Класс приложения выводящий сообщение.
 * @author Nikita Matsnev
 * @version 1.0.1
*/
public class App {
    public static void main(String[] args){

        final int MATRIX_HEIGHT = 3;
        final int MATRIX_WIDTH = 3;

        // Task 1

        System.out.println("Starting project");

        // Task 2

        byte v_byte = 120;
        short v_short = 129;
        char v_char = 'a'; // add ''
        int v_int = 65999;
        long v_long = Long.parseUnsignedLong("4294967296"); // var is overflow
        float v_float = 0.33333334f; // add f 
        double v_double = 0.33333333333;
        boolean v_boolean = true; // change var name

        System.out.println("v_byte: " + v_byte);
        System.out.println("v_short: " + v_short);
        System.out.println("v_char: " + v_char);
        System.out.println("v_int: " + v_int);
        System.out.println("v_long: " + v_long);
        System.out.println("v_float: " + v_float);
        System.out.println("v_double: " + v_double);
        System.out.println("v_boolean: " + v_boolean);

        // Task 3

        for (char i = 'a'; i <= 'z'; i++) {
            System.out.print(i + " ");
        }
        System.out.println("");

        long begini = new java.util.Date().getTime();
        int i = 0;
        for (i = 1; i < 10_000_000; i++) {
        }
        long endi = new java.util.Date().getTime();
        System.out.println("int i, time: " + (endi - begini));

        long beginl = new java.util.Date().getTime();
        long l = 0;
        for (l = 1; l < 10_000_000; l++) {
        }
        long endl= new java.util.Date().getTime();
        System.out.println("long l, time: " + (endl - beginl));

        // Task 4 (5 - 1) 0_O

        int[] mas = { 321, 12, 21, -312, 54, 34, 2, 43 };

        int max = Integer.MIN_VALUE;

        for (int value : mas) {
            if (value > max) {
                max = value;
            }
        }

        System.out.println("Max: " + max);
        
        // Task 5 (5 - 2) 0_O

        int[][] matrix = new int[MATRIX_HEIGHT][MATRIX_WIDTH];

        System.out.println("Initial Matrix");

        for (int col = 0; col < MATRIX_HEIGHT; col++) {
            for (int row = 0; row < MATRIX_WIDTH; row++) {
                matrix[col][row] = (int) Math.round(Math.random() * 10);
                System.out.print(matrix[col][row] + " ");
            }
            System.out.println();
        }

        System.out.println("Transparated Matrix");

        int[][] transpMatrix = new int[MATRIX_HEIGHT][MATRIX_WIDTH];

        for (int col = 0; col < MATRIX_HEIGHT; col++) {
            for (int row = 0; row < MATRIX_WIDTH; row++) {
                transpMatrix[row][col] = matrix[col][row];
                System.out.print(matrix[col][row] + " ");
            }
            System.out.println();
        }
    }
}
